# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/three',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/three',
                'lib_path': 'three'},
  'syms': {'three.core': {'three.core.foo': ('core.html#foo', 'three/core.py')}}}
